### ISSUE TITLE
parcel_css 1.0.0-alpha.32 fails to compile with parcel_selectors 0.24.9 (E0599 from_vec2), blocking frontend builds via tailwind-rs

### ISSUE THREAD

**Issue by loid345** [cloud-shuttle/tailwind-rs#5]
### Summary

Our workspace frontend builds are blocked by an upstream dependency mismatch in the CSS toolchain:

- `tailwind-rs` depends on `parcel_css`
- `parcel_css` resolves to `1.0.0-alpha.32`
- that version depends on `parcel_selectors` (`0.24.9` in our lockfile)
- compilation fails in `parcel_css` with E0599 (`from_vec2` not found)

This appears to be an upstream compatibility issue between `parcel_css` and `parcel_selectors`, not application code.

### Dependency chain in our lockfile

- `tailwind-rs 0.2.0` -> `parcel_css`​:codex-terminal-citation[codex-terminal-citation]{line_range_start=8336 line_range_end=8344 terminal_chunk_id=see lock extract below】
- `parcel_css 1.0.0-alpha.32` -> `parcel_selectors 0.24.9`

### Observed error (from project review logs)

```text
error[E0599]: no function or associated item named `from_vec2` found for struct `Selector<'i, Impl>`
error: could not compile `parcel_css` (lib) due to 4 previous errors
